# frozen_string_literal: true

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'LidlIrelandBillParserForTextract/version'

Gem::Specification.new do |spec|
  spec.name = 'LidlIrelandBillParserForTextract'
  spec.version = LidlIrelandBillParserForTextract::VERSION
  spec.authors = ['Abhinash']
  spec.email = ['abhinashpati143@gmail.com']

  spec.summary = 'Parses json data for Receipts of Lidl Ireland Stores'
  spec.description = 'Parses the json data of the Lidl Ireland Stores generated by AWS Textract.
                        Input => Json File of the receipt data from textract.
                        OutPut => StoreData Model.
                        StoreData Model Atributes => ProductName :string, ProductQuantity :integer, UnitPrice :float, Discount :float, TotalPrice :float'
  spec.homepage = "https://github.com/abhinashpati/LidlIrelandBillParserForTextract"
  spec.license = 'MIT'

  spec.metadata['allowed_push_host'] = "https://github.com/abhinashpati/LidlIrelandBillParserForTextract"

  spec.metadata['homepage_uri'] = spec.homepage
  spec.metadata['source_code_uri'] = "https://github.com/abhinashpati/LidlIrelandBillParserForTextract"
  spec.metadata['changelog_uri'] = "https://github.com/abhinashpati/LidlIrelandBillParserForTextract/commits/master"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject do |f|
      f.match(%r{^(test|spec|features|.idea)/})
    end
  end
  spec.bindir = 'exe'
  spec.executables = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']

  spec.add_development_dependency 'bundler', '~> 2.0'
  spec.add_development_dependency 'minitest', '~> 5.0'
  spec.add_development_dependency 'rake', '~> 13.0'
end
